"""BloomCard database model."""

from datetime import datetime
from typing import Any
from uuid import uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import ARRAY, Column, DateTime, Float, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID

from app.core.database import Base


class BloomCard(Base):
    """
    The unified content model for all card types.

    Supports polymorphic content through the data_payload JSONB field:
    - OWID: {"chart_type": "line", "years": [...], "values": [...], "unit": "%"}
    - CARI: {"image_url": "...", "aspect_ratio": 0.75, "palette": ["#hex"]}
    - OpenAlex: {"abstract": "...", "authors": [...], "pdf_url": "..."}
    - Neocities: {"screenshot_url": "...", "excerpt": "...", "tags": [...]}
    """

    __tablename__ = "bloom_cards"

    # Primary identification
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    source_type = Column(
        String(50),
        nullable=False,
        index=True,
        comment="OWID, OPENALEX, CARI, NEOCITIES, TVTROPES, MOOC",
    )

    # Core content
    title = Column(Text, nullable=False)
    summary = Column(Text, nullable=True, comment="Generated by LLM for aesthetics/science")
    original_url = Column(Text, nullable=False)

    # Polymorphic payload
    data_payload = Column(
        JSONB,
        nullable=False,
        comment="Source-specific data structure (charts, images, abstracts, etc.)",
    )

    # Perspective Engine metadata
    bias_score = Column(
        Float,
        nullable=True,
        comment="0.0 to 1.0 (Right to Left per PoliticalBiasBERT)",
    )
    constructiveness_score = Column(
        Float,
        nullable=True,
        comment="0.0 to 100.0 (Higher = more constructive)",
    )
    blindspot_tags = Column(
        ARRAY(Text),
        nullable=True,
        comment="e.g., ['conservative-blindspot', 'global-south-blindspot']",
    )

    # Bloom Logic (for serendipity scoring)
    embedding = Column(
        Vector(384),  # Sentence-BERT all-MiniLM-L6-v2 produces 384-dim vectors
        nullable=True,
        comment="SBERT embedding for semantic similarity",
    )

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self) -> str:
        return f"<BloomCard(id={self.id}, source={self.source_type}, title='{self.title[:50]}...')>"

    def to_dict(self, include_meta: bool = True, reason_tag: str | None = None) -> dict[str, Any]:
        """
        Convert to dictionary for API responses.

        Args:
            include_meta: Include perspective metadata (bias, constructiveness, reason)
            reason_tag: Serendipity reason tag (e.g., "BLINDSPOT_BREAKER")

        Returns:
            Dictionary representation for API
        """
        data = {
            "id": str(self.id),
            "source_type": self.source_type,
            "title": self.title,
            "summary": self.summary,
            "original_url": self.original_url,
            "data_payload": self.data_payload,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }

        # Include perspective metadata for frontend flip overlay
        if include_meta:
            data["meta"] = {
                "bias_score": self.bias_score if self.bias_score is not None else 0.0,
                "constructiveness_score": (
                    self.constructiveness_score
                    if self.constructiveness_score is not None
                    else 50.0
                ),
                "blindspot_tags": self.blindspot_tags or [],
                "reason_tag": reason_tag or "RECENT",  # Default to recent if no serendipity context
            }

        return data
