"""Initial bloom_cards table

Revision ID: 001
Revises:
Create Date: 2025-11-19 01:00:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create bloom_cards table with pgvector support."""

    # Create bloom_cards table
    op.create_table(
        'bloom_cards',
        sa.Column('id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('source_type', sa.String(50), nullable=False, comment='OWID, OPENALEX, CARI, NEOCITIES, TVTROPES, MOOC'),
        sa.Column('title', sa.Text(), nullable=False),
        sa.Column('summary', sa.Text(), nullable=True, comment='Generated by LLM for aesthetics/science'),
        sa.Column('original_url', sa.Text(), nullable=False),
        sa.Column('data_payload', JSONB, nullable=False, comment='Source-specific data structure'),
        sa.Column('bias_score', sa.Float(), nullable=True, comment='0.0 to 1.0 (Right to Left)'),
        sa.Column('constructiveness_score', sa.Float(), nullable=True, comment='0.0 to 100.0'),
        sa.Column('blindspot_tags', ARRAY(sa.Text()), nullable=True),
        sa.Column('embedding', Vector(384), nullable=True, comment='SBERT embedding for semantic similarity'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    )

    # Create indexes for performance
    op.create_index('ix_bloom_cards_source_type', 'bloom_cards', ['source_type'])
    op.create_index('ix_bloom_cards_created_at', 'bloom_cards', ['created_at'])

    # Create GIN index for JSONB queries
    op.create_index('ix_bloom_cards_data_payload', 'bloom_cards', ['data_payload'], postgresql_using='gin')


def downgrade() -> None:
    """Drop bloom_cards table."""
    op.drop_index('ix_bloom_cards_data_payload', table_name='bloom_cards')
    op.drop_index('ix_bloom_cards_created_at', table_name='bloom_cards')
    op.drop_index('ix_bloom_cards_source_type', table_name='bloom_cards')
    op.drop_table('bloom_cards')
