apiVersion: v1
kind: Service
metadata:
  name: bloom-scroll-api
  namespace: bloom-scroll
spec:
  type: ClusterIP
  selector:
    app: bloom-scroll-api
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
