apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bloom-scroll
resources:
- namespace.yaml
- db-init-job.yaml
- api-deployment.yaml
- api-service.yaml
- ingest-cronjob.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:033e64181edd31dbfdc0592508932814364377adbb9a791de5a76de857aa3dad
  name: ghcr.io/madfam-org/bloom-scroll/api
  newName: ghcr.io/madfam-org/bloom-scroll/api
- digest: sha256:f8c15a0f652368e0630d9f613b231eaec67f9419056412c17e9a5f0c03b2717a
  name: ghcr.io/madfam-org/bloom-scroll/web
  newName: ghcr.io/madfam-org/bloom-scroll/web
