apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bloom-scroll
resources:
- namespace.yaml
- db-init-job.yaml
- api-deployment.yaml
- api-service.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:70368afa2bd624b4ed61b12b23a7c0004f1f6befca74eb2ee6278598c9fcf84e
  name: ghcr.io/madfam-org/bloom-scroll/api
  newName: ghcr.io/madfam-org/bloom-scroll/api
- digest: sha256:05c726939e02a7a9a35ffb1d398f104a5848abd353a7e968ba4c23dc2fd4ca96
  name: ghcr.io/madfam-org/bloom-scroll/web
  newName: ghcr.io/madfam-org/bloom-scroll/web
