apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bloom-scroll
resources:
- namespace.yaml
- db-init-job.yaml
- api-deployment.yaml
- api-service.yaml
- ingest-cronjob.yaml
- web-deployment.yaml
- web-service.yaml
- network-policies.yaml
images:
- digest: sha256:e72358b90da5d05dd385497007e3ee7963207edc0224fe51509c7f2db59dfefe
  name: ghcr.io/madfam-org/bloom-scroll/api
  newName: ghcr.io/madfam-org/bloom-scroll/api
- digest: sha256:4f01cc02756c406bb53bbcc31c02b8f3a9bd36f2c4e6cbb2a18572d97c92af01
  name: ghcr.io/madfam-org/bloom-scroll/web
  newName: ghcr.io/madfam-org/bloom-scroll/web
